---- OBJTYPE
INSERT INTO "MONOPOLY"."OBJTYPE" (OBJECT_TYPE_ID, CODE, NAME) VALUES ('1', 'GameSession', 'GameSession');
INSERT INTO "MONOPOLY"."OBJTYPE" (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME) VALUES ('2', '1', 'Board', 'Board');
INSERT INTO "MONOPOLY"."OBJTYPE" (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME) VALUES ('4', '2', 'Player', 'Player');
INSERT INTO "MONOPOLY"."OBJTYPE" (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME) VALUES ('3', '2', 'PropertyCell', 'PropertyCell');
INSERT INTO "MONOPOLY"."OBJTYPE" (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME) VALUES ('5', '3', 'Building', 'Building');
INSERT INTO "MONOPOLY"."OBJTYPE" (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME) VALUES ('6', '2', 'EventCell', 'EventCell');
INSERT INTO "MONOPOLY"."OBJTYPE" (OBJECT_TYPE_ID, CODE, NAME) VALUES ('7', 'User', 'User');
INSERT INTO "MONOPOLY"."OBJTYPE" (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME) VALUES ('8', '1', 'UserIOMap', 'UserIO');
INSERT INTO "MONOPOLY"."OBJTYPE" (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME) VALUES ('9', '8', 'WebIO', 'WebIO');
INSERT INTO "MONOPOLY"."OBJTYPE" (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME) VALUES ('10', '6', 'Event', 'Event');
INSERT INTO "MONOPOLY"."OBJTYPE" (OBJECT_TYPE_ID, PARENT_ID, CODE, NAME) VALUES ('11', '9', 'Message', 'Message');
----
---- ATTRTYPE
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) 
  VALUES ('1', '2', '4', 'currentPlayer', 'currentPlayer');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('2', '6', 'event', 'event');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('3', '4', 'doublesCount', 'doublesCount');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('4', '4', 'jailStatus', 'jailStatus');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('5', '4', 'jailTerm', 'jailTerm');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('6', '4', 'name', 'name');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('7', '4', 'offerADeal', 'offerADeal');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('8', '4', 'payRent', 'payRent');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('9', '4', 'position', 'position');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) 
  VALUES ('10', '4', '3', 'property_ref', 'property_ref');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('11', '4', 'status', 'status');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('12', '4', 'wallet', 'wallet');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('13', '3', 'basePrice', 'basePrice');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('14', '3', 'baseRent', 'baseRent');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('15', '3', 'description', 'description');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('16', '3', 'maxLevel', 'maxLevel');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('17', '3', 'monopoly', 'monopoly');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('18', '3', 'name', 'name');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('19', '3', 'payBackMoney', 'payBackMoney');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('20', '3', 'pledgePercent', 'pledgePercent');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('21', '3', 'position', 'position');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('22', '3', 'status', 'status');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('23', '3', 'turnsToPayBack', 'turnsToPayBack');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('24', '5', 'currentLevel', 'currentLevel');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('25', '5', 'currentPrice', 'currentPrice');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('26', '5', 'description', 'description');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('27', '5', 'maxLevel', 'maxLevel');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('28', '5', 'name', 'name');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('29', '5', 'primaryCost', 'primaryCost');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) 
  VALUES ('30', '8', '7', 'user_ref', 'user_ref');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('31', '9', 'message', 'message');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME) 
  VALUES ('32', '9', '4', 'player_ref', 'player_ref');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('33', '9', 'warning', 'warning');
--INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('34', '10', 'value', 'value');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('35', '7', 'email', 'email');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('36', '7', 'hash', 'hash');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('37', '7', 'name', 'name');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('38', '7', 'password', 'password');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('39', '1', 'id', 'id');
INSERT INTO "MONOPOLY"."ATTRTYPE" (ATTR_ID, OBJECT_TYPE_ID, CODE, NAME) VALUES ('40', '11', 'value', 'value');









